#!/usr/bin/env tsx
import * as fs from "fs"
import * as path from "path"
import { iconLibraries, type IconLibraryName } from "shadcn/icons"

type IconUsage = Record<IconLibraryName, Set<string>>

// Canonical (lucide) icon name -> { library: icon name }.
type IconMapping = Record<string, Record<string, string>>

function findTsxFiles(dir: string) {
  const files: string[] = []
  // Sort for a deterministic scan order: mapping conflicts resolve to the
  // first occurrence, which must not depend on filesystem enumeration order.
  const entries = fs
    .readdirSync(dir, { withFileTypes: true })
    .sort((a, b) => a.name.localeCompare(b.name))

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      files.push(...findTsxFiles(fullPath))
    } else if (entry.isFile() && entry.name.endsWith(".tsx")) {
      files.push(fullPath)
    }
  }

  return files
}

function scanIconUsage() {
  const iconUsage: IconUsage = Object.keys(iconLibraries).reduce((acc, key) => {
    acc[key as IconLibraryName] = new Set()
    return acc
  }, {} as IconUsage)
  const iconMapping: IconMapping = {}
  // Keyed to dedupe: the same conflict shows up once per placeholder
  // occurrence across bases, but only the first file is worth reporting.
  const warnings = new Map<string, string>()

  const registryBasesDir = path.join(process.cwd(), "registry/bases")
  const files = findTsxFiles(registryBasesDir)
  const libraryNames = Object.values(iconLibraries)
    .map((lib) => lib.name)
    .join("|")
  const iconPlaceholderRegex = new RegExp(
    `<IconPlaceholder\\s+([^>]*?)(?:${libraryNames})=["']([^"']+)["']([^>]*?)\\/?>`,
    "g"
  )

  for (const file of files) {
    const content = fs.readFileSync(file, "utf-8")

    let match
    while ((match = iconPlaceholderRegex.exec(content)) !== null) {
      const fullMatch = match[0]
      const placeholderIcons: Partial<Record<IconLibraryName, string>> = {}

      for (const [libraryName, config] of Object.entries(iconLibraries)) {
        const attrMatch = fullMatch.match(
          new RegExp(`${config.name}=["']([^"']+)["']`)
        )
        if (attrMatch) {
          iconUsage[libraryName as IconLibraryName].add(attrMatch[1])
          placeholderIcons[libraryName as IconLibraryName] = attrMatch[1]
        }
      }

      // Lucide is the canonical key: every placeholder has a lucide prop.
      const canonical = placeholderIcons.lucide
      if (!canonical) {
        const relativeFile = path.relative(process.cwd(), file)
        warnings.set(
          `missing-lucide|${relativeFile}`,
          `IconPlaceholder without a lucide prop in ${relativeFile}`
        )
        continue
      }

      const entry = (iconMapping[canonical] ??= {})
      for (const [libraryName, iconName] of Object.entries(placeholderIcons)) {
        if (entry[libraryName] && entry[libraryName] !== iconName) {
          const key = `conflict|${libraryName}|${canonical}|${iconName}`
          if (!warnings.has(key)) {
            warnings.set(
              key,
              `Conflicting ${libraryName} mapping for ${canonical}: keeping ${entry[libraryName]}, ignoring ${iconName} (first seen in ${path.relative(process.cwd(), file)})`
            )
          }
          continue
        }
        entry[libraryName] = iconName
      }
    }
  }

  return {
    iconUsage,
    iconMapping,
    warnings: Array.from(warnings.values()),
  }
}

function generateIconFiles(iconUsage: IconUsage) {
  const outputDir = path.join(process.cwd(), "registry/icons")

  const written: string[] = []

  Object.entries(iconLibraries).forEach(([libraryName, config]) => {
    const icons = Array.from(iconUsage[libraryName as IconLibraryName]).sort()

    if (icons.length === 0) {
      return
    }

    const content = `// Auto-generated by scripts/build-icons.ts
${icons.map((icon) => `export { ${icon} } from "${config.export}"`).join("\n")}
`

    const filename = `__${libraryName}__.ts`
    const filepath = path.join(outputDir, filename)

    // Skip unchanged files to avoid mtime bumps that trigger
    // unnecessary Turbopack invalidations in watch mode.
    if (
      fs.existsSync(filepath) &&
      fs.readFileSync(filepath, "utf-8") === content
    ) {
      return
    }

    fs.writeFileSync(filepath, content)
    written.push(`  - ${config.title}: ${icons.length} icons`)
  })

  if (written.length > 0) {
    console.log("✓ Generated icon files:")
    written.forEach((line) => console.log(line))
  }
}

function generateIconMapping(iconMapping: IconMapping, warnings: string[]) {
  const legacyPath = path.join(
    process.cwd(),
    "registry/icons/legacy-mapping.json"
  )
  const legacy: IconMapping = JSON.parse(fs.readFileSync(legacyPath, "utf-8"))

  const output: IconMapping = {}
  const scanned: IconMapping = { ...iconMapping }
  const libraryOrder = Object.keys(iconLibraries)

  // Legacy entries come first with their lucide/radix values untouched:
  // published CLI versions reverse-lookup this file by first match, so
  // entry order and legacy values are a compatibility contract.
  for (const [canonical, legacyEntry] of Object.entries(legacy)) {
    const entry: Record<string, string> = { ...legacyEntry }

    // Registry code uses lucide's suffixed aliases (e.g. CheckIcon for Check).
    const scannedKey =
      canonical in scanned
        ? canonical
        : `${canonical}Icon` in scanned
          ? `${canonical}Icon`
          : undefined

    if (scannedKey) {
      for (const library of libraryOrder) {
        if (!entry[library] && scanned[scannedKey][library]) {
          entry[library] = scanned[scannedKey][library]
        }
      }
      delete scanned[scannedKey]
    }

    output[canonical] = entry
  }

  for (const canonical of Object.keys(scanned).sort()) {
    const entry: Record<string, string> = {}
    for (const library of libraryOrder) {
      if (scanned[canonical][library]) {
        entry[library] = scanned[canonical][library]
      }
    }
    output[canonical] = entry
  }

  const outputPath = path.join(process.cwd(), "public/r/icons/index.json")
  const content = JSON.stringify(output, null, 2)

  if (
    fs.existsSync(outputPath) &&
    fs.readFileSync(outputPath, "utf-8") === content
  ) {
    return output
  }

  fs.writeFileSync(outputPath, content)
  console.log(
    `✓ Generated icon mapping: ${Object.keys(output).length} icons (${
      Object.keys(legacy).length
    } legacy)`
  )

  // Only surface scan warnings when the mapping actually changed: they are
  // informational (first occurrence wins) and would otherwise repeat on
  // every rebuild in watch mode.
  if (warnings.length > 0) {
    if (isVerbose) {
      warnings.forEach((warning) => console.warn(`⚠ ${warning}`))
    } else {
      console.warn(
        `⚠ ${warnings.length} icon mapping conflicts (first occurrence wins). Run with --verbose for details.`
      )
    }
  }

  return output
}

async function main() {
  const { iconUsage, iconMapping, warnings } = scanIconUsage()
  generateIconFiles(iconUsage)
  const mapping = generateIconMapping(iconMapping, warnings)
  await generateSiteIcons(mapping)
}

// --- Site icons ---------------------------------------------------------------
// The website's Fabricator previews import Lucide icons from "@/lib/site-icons"
// (the registry build rewrites "lucide-react" in those copies), so they follow
// the icon pack picked in the site settings. This generates that module: one
// component per Lucide icon the previews use, with the matching names in the
// other packs, plus one module per pack with just those icons (loaded on
// demand by lib/site-icons-runtime.tsx). The docs still show "lucide-react".

const SITE_ICON_LIBRARIES = ["tabler", "hugeicons", "phosphor", "remixicon"]

// Sources whose Lucide icons end up in the site's Fabricator previews.
const SITE_ICON_SOURCES = [
  "examples/base",
  "examples/radix",
  "examples/aria",
  "registry/bases/base/ui",
  "registry/bases/radix/ui",
  "registry/bases/aria/ui",
  "registry/fabricator",
  "app/(app)/(root)/_components",
  "components/foundations",
]

const LUCIDE_IMPORT_REGEX =
  /import\s*\{([^}]*)\}\s*from\s*["'](?:lucide-react|@\/lib\/site-icons)["']/g
const LUCIDE_PLACEHOLDER_REGEX =
  /<IconPlaceholder\b[^>]*?\blucide=["']([^"']+)["']/g

function scanSiteIconNames() {
  const names = new Set<string>()
  for (const dir of SITE_ICON_SOURCES) {
    const fullDir = path.join(process.cwd(), dir)
    if (!fs.existsSync(fullDir)) continue
    for (const file of findTsxFiles(fullDir)) {
      const content = fs.readFileSync(file, "utf-8")
      for (const match of content.matchAll(LUCIDE_IMPORT_REGEX)) {
        for (const specifier of match[1].split(",")) {
          const name = specifier
            .trim()
            .split(/\s+as\s+/)[0]
            .trim()
          // Types (LucideIcon, LucideProps) are re-exported as they are.
          if (name && !name.startsWith("type ") && !/^Lucide/.test(name)) {
            names.add(name)
          }
        }
      }
      for (const match of content.matchAll(LUCIDE_PLACEHOLDER_REGEX)) {
        names.add(match[1])
      }
    }
  }
  return Array.from(names).sort()
}

function exportedNames(file: string) {
  if (!fs.existsSync(file)) return new Set<string>()
  return new Set(
    Array.from(
      fs.readFileSync(file, "utf-8").matchAll(/export \{ (\w+) \}/g),
      (match) => match[1]
    )
  )
}

async function generateSiteIcons(mapping: IconMapping) {
  const siteMapping: IconMapping = JSON.parse(
    fs.readFileSync(
      path.join(process.cwd(), "registry/icons/site-mapping.json"),
      "utf-8"
    )
  )
  delete siteMapping.$comment

  const lookup = (name: string) => {
    const candidates = [
      name,
      name.replace(/Icon$/, ""),
      name.endsWith("Icon") ? name : `${name}Icon`,
    ]
    const entry: Record<string, string> = {}
    for (const source of [siteMapping, mapping]) {
      for (const candidate of candidates) {
        for (const library of SITE_ICON_LIBRARIES) {
          const value = source[candidate]?.[library]
          if (value && !entry[library]) entry[library] = value
        }
      }
    }
    return entry
  }

  const names = scanSiteIconNames()
  const entries = names.map((name) => ({ name, mapping: lookup(name) }))
  const libDir = path.join(process.cwd(), "lib")

  // Names must exist in the installed packs. Names already in a generated
  // module were checked when it was written; only new ones load the package.
  for (const library of SITE_ICON_LIBRARIES) {
    const file = path.join(libDir, `site-icons.${library}.ts`)
    const known = exportedNames(file)
    const unknown = entries
      .map((entry) => entry.mapping[library])
      .filter((value): value is string => !!value && !known.has(value))
    if (unknown.length === 0) continue
    const config = iconLibraries[library as IconLibraryName]
    const available = new Set(Object.keys(await import(config.export)))
    for (const entry of entries) {
      const value = entry.mapping[library]
      if (value && !known.has(value) && !available.has(value)) {
        console.warn(
          `⚠ Site icons: ${config.export} has no ${value} (for ${entry.name}); it falls back to Lucide.`
        )
        delete entry.mapping[library]
      }
    }
  }

  const header = "// Auto-generated by scripts/build-icons.ts. Do not edit.\n"
  const files: Record<string, string> = {}

  files["site-icons.tsx"] = `${header}"use client"

import {
${names.map((name) => `  ${name} as Lucide${name},`).join("\n")}
} from "lucide-react"

import { createSiteIcon } from "@/lib/site-icons-runtime"

export type { LucideIcon, LucideProps } from "lucide-react"

${entries
  .map(
    ({ name, mapping }) =>
      `export const ${name} = createSiteIcon(Lucide${name}, ${JSON.stringify(
        mapping
      )})`
  )
  .join("\n")}
`

  for (const library of SITE_ICON_LIBRARIES) {
    const config = iconLibraries[library as IconLibraryName]
    const icons = Array.from(
      new Set(
        entries
          .map((entry) => entry.mapping[library])
          .filter((value): value is string => !!value)
      )
    ).sort()
    files[`site-icons.${library}.ts`] = `${header}${icons
      .map((icon) => `export { ${icon} } from "${config.export}"`)
      .join("\n")}
`
  }

  const { format, resolveConfig } = await import("prettier")
  const written: string[] = []
  for (const [filename, raw] of Object.entries(files)) {
    const filepath = path.join(libDir, filename)
    const content = await format(raw, {
      ...(await resolveConfig(filepath)),
      filepath,
    })
    if (
      fs.existsSync(filepath) &&
      fs.readFileSync(filepath, "utf-8") === content
    ) {
      continue
    }
    fs.writeFileSync(filepath, content)
    written.push(filename)
  }

  if (written.length > 0) {
    const mapped = entries.filter(
      (entry) =>
        Object.keys(entry.mapping).length === SITE_ICON_LIBRARIES.length
    ).length
    console.log(
      `✓ Generated site icons: ${names.length} icons, ${mapped} in every pack (${written.join(", ")})`
    )
  }
}

const isWatchMode = process.argv.includes("--watch")
const isVerbose = process.argv.includes("--verbose")

if (isWatchMode) {
  const REGISTRY_DIR = path.join(process.cwd(), "registry/bases")

  async function startWatcher() {
    const { default: chokidar } = await import("chokidar")

    await main()

    const watcher = chokidar.watch(REGISTRY_DIR, {
      ignored: /(^|[/\\])\../,
      persistent: true,
      ignoreInitial: true,
    })

    const rebuild = (filename: string) => {
      if (!filename.endsWith(".tsx")) return

      main().catch((error) => {
        console.error("❌ Icons build failed:", error)
      })
    }

    watcher.on("error", (error) => {
      console.error("❌ Watcher error:", error)
    })

    watcher.on("change", rebuild)
    watcher.on("add", rebuild)

    process.on("SIGINT", async () => {
      await watcher.close()
      process.exit(0)
    })
  }

  startWatcher()
} else {
  await main()
}
