// Auto-generated by scripts/build-icons.ts. Do not edit.
"use client"

import {
  AlertCircleIcon as LucideAlertCircleIcon,
  AlertTriangleIcon as LucideAlertTriangleIcon,
  AlignCenterIcon as LucideAlignCenterIcon,
  AlignLeftIcon as LucideAlignLeftIcon,
  AlignRightIcon as LucideAlignRightIcon,
  AppWindowIcon as LucideAppWindowIcon,
  ArchiveIcon as LucideArchiveIcon,
  ArrowDownIcon as LucideArrowDownIcon,
  ArrowLeftIcon as LucideArrowLeftIcon,
  ArrowRightIcon as LucideArrowRightIcon,
  ArrowUpDown as LucideArrowUpDown,
  ArrowUpDownIcon as LucideArrowUpDownIcon,
  ArrowUpIcon as LucideArrowUpIcon,
  ArrowUpRightIcon as LucideArrowUpRightIcon,
  AudioLinesIcon as LucideAudioLinesIcon,
  AudioWaveform as LucideAudioWaveform,
  BadgeCheck as LucideBadgeCheck,
  BadgeCheckIcon as LucideBadgeCheckIcon,
  Bell as LucideBell,
  BellIcon as LucideBellIcon,
  BluetoothIcon as LucideBluetoothIcon,
  Bold as LucideBold,
  BoldIcon as LucideBoldIcon,
  BookmarkIcon as LucideBookmarkIcon,
  BookOpen as LucideBookOpen,
  BookOpenCheck as LucideBookOpenCheck,
  BookOpenIcon as LucideBookOpenIcon,
  Bot as LucideBot,
  BotIcon as LucideBotIcon,
  BoxIcon as LucideBoxIcon,
  Building2Icon as LucideBuilding2Icon,
  Calculator as LucideCalculator,
  CalculatorIcon as LucideCalculatorIcon,
  Calendar as LucideCalendar,
  CalendarIcon as LucideCalendarIcon,
  CalendarPlusIcon as LucideCalendarPlusIcon,
  ChartBarIcon as LucideChartBarIcon,
  ChartLineIcon as LucideChartLineIcon,
  ChartPieIcon as LucideChartPieIcon,
  CheckCircle2Icon as LucideCheckCircle2Icon,
  CheckIcon as LucideCheckIcon,
  ChevronDown as LucideChevronDown,
  ChevronDownIcon as LucideChevronDownIcon,
  ChevronLeftIcon as LucideChevronLeftIcon,
  ChevronRight as LucideChevronRight,
  ChevronRightIcon as LucideChevronRightIcon,
  ChevronsUpDown as LucideChevronsUpDown,
  ChevronsUpDownIcon as LucideChevronsUpDownIcon,
  ChevronUpIcon as LucideChevronUpIcon,
  CircleAlertIcon as LucideCircleAlertIcon,
  CircleCheckIcon as LucideCircleCheckIcon,
  CircleDashedIcon as LucideCircleDashedIcon,
  CircleFadingArrowUpIcon as LucideCircleFadingArrowUpIcon,
  CircleFadingPlusIcon as LucideCircleFadingPlusIcon,
  ClipboardPasteIcon as LucideClipboardPasteIcon,
  Clock2Icon as LucideClock2Icon,
  ClockIcon as LucideClockIcon,
  CodeIcon as LucideCodeIcon,
  Command as LucideCommand,
  CopyIcon as LucideCopyIcon,
  CreditCard as LucideCreditCard,
  CreditCardIcon as LucideCreditCardIcon,
  DotIcon as LucideDotIcon,
  DownloadIcon as LucideDownloadIcon,
  ExternalLinkIcon as LucideExternalLinkIcon,
  EyeIcon as LucideEyeIcon,
  EyeOffIcon as LucideEyeOffIcon,
  FileCodeIcon as LucideFileCodeIcon,
  FileIcon as LucideFileIcon,
  FileSearchIcon as LucideFileSearchIcon,
  FileTextIcon as LucideFileTextIcon,
  FileWarningIcon as LucideFileWarningIcon,
  Folder as LucideFolder,
  FolderIcon as LucideFolderIcon,
  FolderOpenIcon as LucideFolderOpenIcon,
  FolderPlusIcon as LucideFolderPlusIcon,
  FolderSearchIcon as LucideFolderSearchIcon,
  Forward as LucideForward,
  Frame as LucideFrame,
  FrameIcon as LucideFrameIcon,
  GalleryVerticalEnd as LucideGalleryVerticalEnd,
  GitBranchIcon as LucideGitBranchIcon,
  GlobeIcon as LucideGlobeIcon,
  HelpCircle as LucideHelpCircle,
  HelpCircleIcon as LucideHelpCircleIcon,
  HistoryIcon as LucideHistoryIcon,
  HomeIcon as LucideHomeIcon,
  ImageIcon as LucideImageIcon,
  InboxIcon as LucideInboxIcon,
  InfoIcon as LucideInfoIcon,
  Italic as LucideItalic,
  ItalicIcon as LucideItalicIcon,
  KeyboardIcon as LucideKeyboardIcon,
  LanguagesIcon as LucideLanguagesIcon,
  LayersIcon as LucideLayersIcon,
  LayoutGridIcon as LucideLayoutGridIcon,
  LayoutIcon as LucideLayoutIcon,
  LifeBuoyIcon as LucideLifeBuoyIcon,
  Link2Icon as LucideLink2Icon,
  ListFilterIcon as LucideListFilterIcon,
  ListIcon as LucideListIcon,
  Loader2Icon as LucideLoader2Icon,
  LoaderIcon as LucideLoaderIcon,
  LogOut as LucideLogOut,
  LogOutIcon as LucideLogOutIcon,
  MailCheckIcon as LucideMailCheckIcon,
  MailIcon as LucideMailIcon,
  Map as LucideMap,
  MapIcon as LucideMapIcon,
  MaximizeIcon as LucideMaximizeIcon,
  MessageCircleDashedIcon as LucideMessageCircleDashedIcon,
  MessageSquareIcon as LucideMessageSquareIcon,
  MicIcon as LucideMicIcon,
  MinimizeIcon as LucideMinimizeIcon,
  Minus as LucideMinus,
  MinusIcon as LucideMinusIcon,
  MonitorIcon as LucideMonitorIcon,
  MoonIcon as LucideMoonIcon,
  MoreHorizontal as LucideMoreHorizontal,
  MoreHorizontalIcon as LucideMoreHorizontalIcon,
  OctagonXIcon as LucideOctagonXIcon,
  PaletteIcon as LucidePaletteIcon,
  PanelLeftCloseIcon as LucidePanelLeftCloseIcon,
  PanelLeftIcon as LucidePanelLeftIcon,
  PanelLeftOpenIcon as LucidePanelLeftOpenIcon,
  PaperclipIcon as LucidePaperclipIcon,
  PencilIcon as LucidePencilIcon,
  PieChart as LucidePieChart,
  PieChartIcon as LucidePieChartIcon,
  Plus as LucidePlus,
  PlusIcon as LucidePlusIcon,
  RadioIcon as LucideRadioIcon,
  RectangleHorizontalIcon as LucideRectangleHorizontalIcon,
  RectangleVerticalIcon as LucideRectangleVerticalIcon,
  RefreshCcwIcon as LucideRefreshCcwIcon,
  RefreshCwIcon as LucideRefreshCwIcon,
  RotateCcwIcon as LucideRotateCcwIcon,
  RotateCwIcon as LucideRotateCwIcon,
  SaveIcon as LucideSaveIcon,
  ScissorsIcon as LucideScissorsIcon,
  Search as LucideSearch,
  SearchIcon as LucideSearchIcon,
  SendIcon as LucideSendIcon,
  Settings as LucideSettings,
  Settings2 as LucideSettings2,
  SettingsIcon as LucideSettingsIcon,
  ShareIcon as LucideShareIcon,
  ShieldAlertIcon as LucideShieldAlertIcon,
  ShieldIcon as LucideShieldIcon,
  Smile as LucideSmile,
  SmileIcon as LucideSmileIcon,
  Sparkles as LucideSparkles,
  SparklesIcon as LucideSparklesIcon,
  SquareIcon as LucideSquareIcon,
  SquarePenIcon as LucideSquarePenIcon,
  SquareTerminal as LucideSquareTerminal,
  SquareTerminalIcon as LucideSquareTerminalIcon,
  StarIcon as LucideStarIcon,
  SunIcon as LucideSunIcon,
  TableIcon as LucideTableIcon,
  TagIcon as LucideTagIcon,
  TelescopeIcon as LucideTelescopeIcon,
  ThumbsDownIcon as LucideThumbsDownIcon,
  ThumbsUpIcon as LucideThumbsUpIcon,
  Trash2 as LucideTrash2,
  Trash2Icon as LucideTrash2Icon,
  TrashIcon as LucideTrashIcon,
  TriangleAlertIcon as LucideTriangleAlertIcon,
  Underline as LucideUnderline,
  UnderlineIcon as LucideUnderlineIcon,
  User as LucideUser,
  UserIcon as LucideUserIcon,
  UserRoundXIcon as LucideUserRoundXIcon,
  UsersIcon as LucideUsersIcon,
  VolumeOffIcon as LucideVolumeOffIcon,
  WalletIcon as LucideWalletIcon,
  XIcon as LucideXIcon,
  ZoomInIcon as LucideZoomInIcon,
  ZoomOutIcon as LucideZoomOutIcon,
} from "lucide-react"

import { createSiteIcon } from "@/lib/site-icons-runtime"

export type { LucideIcon, LucideProps } from "lucide-react"

export const AlertCircleIcon = createSiteIcon(LucideAlertCircleIcon, {
  tabler: "IconAlertCircle",
  hugeicons: "AlertCircleIcon",
  phosphor: "WarningCircleIcon",
  remixicon: "RiErrorWarningLine",
})
export const AlertTriangleIcon = createSiteIcon(LucideAlertTriangleIcon, {
  tabler: "IconAlertTriangle",
  hugeicons: "AlertCircleIcon",
  phosphor: "WarningIcon",
  remixicon: "RiErrorWarningLine",
})
export const AlignCenterIcon = createSiteIcon(LucideAlignCenterIcon, {
  tabler: "IconAlignCenter",
  hugeicons: "TextAlignCenterIcon",
  phosphor: "TextAlignCenterIcon",
  remixicon: "RiAlignCenter",
})
export const AlignLeftIcon = createSiteIcon(LucideAlignLeftIcon, {
  tabler: "IconAlignLeft",
  hugeicons: "TextAlignLeftIcon",
  phosphor: "TextAlignLeftIcon",
  remixicon: "RiAlignLeft",
})
export const AlignRightIcon = createSiteIcon(LucideAlignRightIcon, {
  tabler: "IconAlignRight",
  hugeicons: "TextAlignRightIcon",
  phosphor: "TextAlignRightIcon",
  remixicon: "RiAlignRight",
})
export const AppWindowIcon = createSiteIcon(LucideAppWindowIcon, {
  tabler: "IconAppWindow",
  hugeicons: "CursorInWindowIcon",
  phosphor: "AppWindowIcon",
  remixicon: "RiWindowLine",
})
export const ArchiveIcon = createSiteIcon(LucideArchiveIcon, {
  tabler: "IconArchive",
  hugeicons: "Archive02Icon",
  phosphor: "ArchiveIcon",
  remixicon: "RiArchiveLine",
})
export const ArrowDownIcon = createSiteIcon(LucideArrowDownIcon, {
  tabler: "IconArrowDown",
  hugeicons: "ArrowDownIcon",
  phosphor: "ArrowDownIcon",
  remixicon: "RiArrowDownLine",
})
export const ArrowLeftIcon = createSiteIcon(LucideArrowLeftIcon, {
  tabler: "IconArrowLeft",
  hugeicons: "ArrowLeft02Icon",
  phosphor: "ArrowLeftIcon",
  remixicon: "RiArrowLeftLine",
})
export const ArrowRightIcon = createSiteIcon(LucideArrowRightIcon, {
  tabler: "IconArrowRight",
  hugeicons: "ArrowRight01Icon",
  phosphor: "ArrowRightIcon",
  remixicon: "RiArrowRightLine",
})
export const ArrowUpDown = createSiteIcon(LucideArrowUpDown, {
  tabler: "IconArrowsUpDown",
  hugeicons: "ArrowUpDownIcon",
  phosphor: "ArrowsDownUpIcon",
  remixicon: "RiArrowUpDownLine",
})
export const ArrowUpDownIcon = createSiteIcon(LucideArrowUpDownIcon, {
  tabler: "IconArrowsUpDown",
  hugeicons: "ArrowUpDownIcon",
  phosphor: "ArrowsDownUpIcon",
  remixicon: "RiArrowUpDownLine",
})
export const ArrowUpIcon = createSiteIcon(LucideArrowUpIcon, {
  tabler: "IconArrowUp",
  hugeicons: "ArrowUpIcon",
  phosphor: "ArrowUpIcon",
  remixicon: "RiArrowUpLine",
})
export const ArrowUpRightIcon = createSiteIcon(LucideArrowUpRightIcon, {
  tabler: "IconArrowUpRight",
  hugeicons: "ArrowUpRightIcon",
  phosphor: "ArrowUpRightIcon",
  remixicon: "RiArrowRightUpLine",
})
export const AudioLinesIcon = createSiteIcon(LucideAudioLinesIcon, {
  tabler: "IconPlayerRecordFilled",
  hugeicons: "AudioWave01Icon",
  phosphor: "RecordIcon",
  remixicon: "RiRecordCircleLine",
})
export const AudioWaveform = createSiteIcon(LucideAudioWaveform, {
  tabler: "IconWaveSine",
  hugeicons: "AudioWave01Icon",
  phosphor: "WaveformIcon",
  remixicon: "RiVoiceprintLine",
})
export const BadgeCheck = createSiteIcon(LucideBadgeCheck, {
  tabler: "IconRosetteDiscountCheck",
  hugeicons: "CheckmarkBadge02Icon",
  phosphor: "CheckCircleIcon",
  remixicon: "RiCheckboxCircleLine",
})
export const BadgeCheckIcon = createSiteIcon(LucideBadgeCheckIcon, {
  tabler: "IconRosetteDiscountCheck",
  hugeicons: "CheckmarkBadgeIcon",
  phosphor: "CheckCircleIcon",
  remixicon: "RiCheckboxCircleLine",
})
export const Bell = createSiteIcon(LucideBell, {
  tabler: "IconNotification",
  hugeicons: "Notification03Icon",
  phosphor: "BellIcon",
  remixicon: "RiNotification3Line",
})
export const BellIcon = createSiteIcon(LucideBellIcon, {
  tabler: "IconNotification",
  hugeicons: "Notification03Icon",
  phosphor: "BellIcon",
  remixicon: "RiNotification3Line",
})
export const BluetoothIcon = createSiteIcon(LucideBluetoothIcon, {
  tabler: "IconBluetooth",
  hugeicons: "BluetoothIcon",
  phosphor: "BluetoothIcon",
  remixicon: "RiBluetoothLine",
})
export const Bold = createSiteIcon(LucideBold, {
  tabler: "IconBold",
  hugeicons: "TextBoldIcon",
  phosphor: "TextBIcon",
  remixicon: "RiBold",
})
export const BoldIcon = createSiteIcon(LucideBoldIcon, {
  tabler: "IconBold",
  hugeicons: "TextBoldIcon",
  phosphor: "TextBIcon",
  remixicon: "RiBold",
})
export const BookOpen = createSiteIcon(LucideBookOpen, {
  tabler: "IconBook",
  hugeicons: "BookOpen02Icon",
  phosphor: "BookOpenIcon",
  remixicon: "RiBookOpenLine",
})
export const BookOpenCheck = createSiteIcon(LucideBookOpenCheck, {
  tabler: "IconBook",
  hugeicons: "BookOpen01Icon",
  phosphor: "BookOpenIcon",
  remixicon: "RiBookOpenLine",
})
export const BookOpenIcon = createSiteIcon(LucideBookOpenIcon, {
  tabler: "IconBook",
  hugeicons: "BookOpen02Icon",
  phosphor: "BookOpenIcon",
  remixicon: "RiBookOpenLine",
})
export const BookmarkIcon = createSiteIcon(LucideBookmarkIcon, {
  tabler: "IconBookmark",
  hugeicons: "BookmarkIcon",
  phosphor: "BookmarkIcon",
  remixicon: "RiBookmarkLine",
})
export const Bot = createSiteIcon(LucideBot, {
  tabler: "IconRobot",
  hugeicons: "RoboticIcon",
  phosphor: "RobotIcon",
  remixicon: "RiRobotLine",
})
export const BotIcon = createSiteIcon(LucideBotIcon, {
  tabler: "IconRobot",
  hugeicons: "RoboticIcon",
  phosphor: "RobotIcon",
  remixicon: "RiRobotLine",
})
export const BoxIcon = createSiteIcon(LucideBoxIcon, {})
export const Building2Icon = createSiteIcon(LucideBuilding2Icon, {
  tabler: "IconBuildingBank",
  hugeicons: "BankIcon",
  phosphor: "BankIcon",
  remixicon: "RiBankLine",
})
export const Calculator = createSiteIcon(LucideCalculator, {
  tabler: "IconCalculator",
  hugeicons: "CalculatorIcon",
  phosphor: "CalculatorIcon",
  remixicon: "RiCalculatorLine",
})
export const CalculatorIcon = createSiteIcon(LucideCalculatorIcon, {
  tabler: "IconCalculator",
  hugeicons: "CalculatorIcon",
  phosphor: "CalculatorIcon",
  remixicon: "RiCalculatorLine",
})
export const Calendar = createSiteIcon(LucideCalendar, {
  tabler: "IconCalendar",
  hugeicons: "Calendar03Icon",
  phosphor: "CalendarIcon",
  remixicon: "RiCalendarLine",
})
export const CalendarIcon = createSiteIcon(LucideCalendarIcon, {
  tabler: "IconCalendar",
  hugeicons: "Calendar03Icon",
  phosphor: "CalendarIcon",
  remixicon: "RiCalendarLine",
})
export const CalendarPlusIcon = createSiteIcon(LucideCalendarPlusIcon, {
  tabler: "IconCalendarPlus",
  hugeicons: "CalendarAdd01Icon",
  phosphor: "CalendarPlusIcon",
  remixicon: "RiCalendarScheduleLine",
})
export const ChartBarIcon = createSiteIcon(LucideChartBarIcon, {
  tabler: "IconChartBar",
  hugeicons: "ChartHistogramIcon",
  phosphor: "ChartBarIcon",
  remixicon: "RiBarChartLine",
})
export const ChartLineIcon = createSiteIcon(LucideChartLineIcon, {
  tabler: "IconChartLine",
  hugeicons: "ChartIcon",
  phosphor: "ChartLineIcon",
  remixicon: "RiLineChartLine",
})
export const ChartPieIcon = createSiteIcon(LucideChartPieIcon, {
  tabler: "IconChartPie",
  hugeicons: "Chart03Icon",
  phosphor: "ChartPieIcon",
  remixicon: "RiPieChartLine",
})
export const CheckCircle2Icon = createSiteIcon(LucideCheckCircle2Icon, {
  tabler: "IconCircleCheckFilled",
  hugeicons: "CheckmarkCircle02Icon",
  phosphor: "CheckCircleIcon",
  remixicon: "RiCheckboxCircleLine",
})
export const CheckIcon = createSiteIcon(LucideCheckIcon, {
  tabler: "IconCheck",
  hugeicons: "Tick02Icon",
  phosphor: "CheckIcon",
  remixicon: "RiCheckLine",
})
export const ChevronDown = createSiteIcon(LucideChevronDown, {
  tabler: "IconChevronDown",
  hugeicons: "ArrowDown01Icon",
  phosphor: "CaretDownIcon",
  remixicon: "RiArrowDownSLine",
})
export const ChevronDownIcon = createSiteIcon(LucideChevronDownIcon, {
  tabler: "IconChevronDown",
  hugeicons: "ArrowDown01Icon",
  phosphor: "CaretDownIcon",
  remixicon: "RiArrowDownSLine",
})
export const ChevronLeftIcon = createSiteIcon(LucideChevronLeftIcon, {
  tabler: "IconChevronLeft",
  hugeicons: "ArrowLeft01Icon",
  phosphor: "CaretLeftIcon",
  remixicon: "RiArrowLeftSLine",
})
export const ChevronRight = createSiteIcon(LucideChevronRight, {
  tabler: "IconChevronRight",
  hugeicons: "ArrowRight01Icon",
  phosphor: "CaretRightIcon",
  remixicon: "RiArrowRightSLine",
})
export const ChevronRightIcon = createSiteIcon(LucideChevronRightIcon, {
  tabler: "IconChevronRight",
  hugeicons: "ArrowRight01Icon",
  phosphor: "CaretRightIcon",
  remixicon: "RiArrowRightSLine",
})
export const ChevronUpIcon = createSiteIcon(LucideChevronUpIcon, {
  tabler: "IconChevronUp",
  hugeicons: "ArrowUp01Icon",
  phosphor: "CaretUpIcon",
  remixicon: "RiArrowUpSLine",
})
export const ChevronsUpDown = createSiteIcon(LucideChevronsUpDown, {
  tabler: "IconSelector",
  hugeicons: "UnfoldMoreIcon",
  phosphor: "CaretUpDownIcon",
  remixicon: "RiArrowUpDownLine",
})
export const ChevronsUpDownIcon = createSiteIcon(LucideChevronsUpDownIcon, {
  tabler: "IconSelector",
  hugeicons: "UnfoldMoreIcon",
  phosphor: "CaretUpDownIcon",
  remixicon: "RiArrowUpDownLine",
})
export const CircleAlertIcon = createSiteIcon(LucideCircleAlertIcon, {
  tabler: "IconExclamationCircle",
  hugeicons: "AlertCircleIcon",
  phosphor: "WarningCircleIcon",
  remixicon: "RiErrorWarningLine",
})
export const CircleCheckIcon = createSiteIcon(LucideCircleCheckIcon, {
  tabler: "IconCircleCheckFilled",
  hugeicons: "CheckmarkCircle01Icon",
  phosphor: "CheckCircleIcon",
  remixicon: "RiCheckboxCircleFill",
})
export const CircleDashedIcon = createSiteIcon(LucideCircleDashedIcon, {
  tabler: "IconCircleDashed",
  hugeicons: "DashedLineCircleIcon",
  phosphor: "CircleDashedIcon",
  remixicon: "RiLoaderLine",
})
export const CircleFadingArrowUpIcon = createSiteIcon(
  LucideCircleFadingArrowUpIcon,
  {
    tabler: "IconCircleArrowUp",
    hugeicons: "CircleArrowUp01Icon",
    phosphor: "ArrowCircleUpIcon",
    remixicon: "RiArrowUpCircleLine",
  }
)
export const CircleFadingPlusIcon = createSiteIcon(LucideCircleFadingPlusIcon, {
  tabler: "IconCircleDashedPlus",
  hugeicons: "AddCircleHalfDotIcon",
  phosphor: "PlusCircleIcon",
  remixicon: "RiAddCircleLine",
})
export const ClipboardPasteIcon = createSiteIcon(LucideClipboardPasteIcon, {
  tabler: "IconClipboard",
  hugeicons: "ClipboardIcon",
  phosphor: "ClipboardIcon",
  remixicon: "RiClipboardLine",
})
export const Clock2Icon = createSiteIcon(LucideClock2Icon, {
  tabler: "IconClockHour2",
  hugeicons: "Clock03Icon",
  phosphor: "ClockIcon",
  remixicon: "RiTimeLine",
})
export const ClockIcon = createSiteIcon(LucideClockIcon, {
  tabler: "IconClock",
  hugeicons: "Clock01Icon",
  phosphor: "ClockIcon",
  remixicon: "RiTimeLine",
})
export const CodeIcon = createSiteIcon(LucideCodeIcon, {
  tabler: "IconCode",
  hugeicons: "CodeIcon",
  phosphor: "CodeIcon",
  remixicon: "RiCodeLine",
})
export const Command = createSiteIcon(LucideCommand, {
  tabler: "IconInnerShadowTop",
  hugeicons: "CommandIcon",
  phosphor: "CommandIcon",
  remixicon: "RiCommandLine",
})
export const CopyIcon = createSiteIcon(LucideCopyIcon, {
  tabler: "IconCopy",
  hugeicons: "Copy01Icon",
  phosphor: "CopyIcon",
  remixicon: "RiFileCopyLine",
})
export const CreditCard = createSiteIcon(LucideCreditCard, {
  tabler: "IconCreditCard",
  hugeicons: "CreditCardIcon",
  phosphor: "CreditCardIcon",
  remixicon: "RiBankCardLine",
})
export const CreditCardIcon = createSiteIcon(LucideCreditCardIcon, {
  tabler: "IconCreditCard",
  hugeicons: "CreditCardIcon",
  phosphor: "CreditCardIcon",
  remixicon: "RiBankCardLine",
})
export const DotIcon = createSiteIcon(LucideDotIcon, {
  tabler: "IconPoint",
  phosphor: "DotIcon",
})
export const DownloadIcon = createSiteIcon(LucideDownloadIcon, {
  tabler: "IconDownload",
  hugeicons: "DownloadIcon",
  phosphor: "DownloadIcon",
  remixicon: "RiDownloadLine",
})
export const ExternalLinkIcon = createSiteIcon(LucideExternalLinkIcon, {
  tabler: "IconExternalLink",
  hugeicons: "LinkSquare02Icon",
  phosphor: "ArrowSquareOutIcon",
  remixicon: "RiExternalLinkLine",
})
export const EyeIcon = createSiteIcon(LucideEyeIcon, {
  tabler: "IconEye",
  hugeicons: "EyeIcon",
  phosphor: "EyeIcon",
  remixicon: "RiEyeLine",
})
export const EyeOffIcon = createSiteIcon(LucideEyeOffIcon, {
  tabler: "IconEyeClosed",
  hugeicons: "ViewOffIcon",
  phosphor: "EyeSlashIcon",
  remixicon: "RiEyeOffLine",
})
export const FileCodeIcon = createSiteIcon(LucideFileCodeIcon, {
  tabler: "IconFileCode",
  hugeicons: "File01Icon",
  phosphor: "FileCodeIcon",
  remixicon: "RiFileCodeLine",
})
export const FileIcon = createSiteIcon(LucideFileIcon, {
  tabler: "IconFileWord",
  hugeicons: "File01Icon",
  phosphor: "FileIcon",
  remixicon: "RiFileLine",
})
export const FileSearchIcon = createSiteIcon(LucideFileSearchIcon, {
  tabler: "IconFileSearch",
  hugeicons: "FileSearchIcon",
  phosphor: "FileSearchIcon",
  remixicon: "RiFileSearchLine",
})
export const FileTextIcon = createSiteIcon(LucideFileTextIcon, {
  tabler: "IconFileDescription",
  hugeicons: "File01Icon",
  phosphor: "FileTextIcon",
  remixicon: "RiFileTextLine",
})
export const FileWarningIcon = createSiteIcon(LucideFileWarningIcon, {
  tabler: "IconFileAlert",
  hugeicons: "FileCorruptIcon",
  phosphor: "FileXIcon",
  remixicon: "RiFileWarningLine",
})
export const Folder = createSiteIcon(LucideFolder, {
  tabler: "IconFolder",
  hugeicons: "Folder01Icon",
  phosphor: "FolderIcon",
  remixicon: "RiFolderLine",
})
export const FolderIcon = createSiteIcon(LucideFolderIcon, {
  tabler: "IconFolder",
  hugeicons: "Folder01Icon",
  phosphor: "FolderIcon",
  remixicon: "RiFolderLine",
})
export const FolderOpenIcon = createSiteIcon(LucideFolderOpenIcon, {
  tabler: "IconFolderOpen",
  hugeicons: "FolderOpenIcon",
  phosphor: "FolderOpenIcon",
  remixicon: "RiFolderOpenLine",
})
export const FolderPlusIcon = createSiteIcon(LucideFolderPlusIcon, {
  tabler: "IconFolderPlus",
  hugeicons: "FolderAddIcon",
  phosphor: "FolderPlusIcon",
  remixicon: "RiFolderAddLine",
})
export const FolderSearchIcon = createSiteIcon(LucideFolderSearchIcon, {
  tabler: "IconFolderSearch",
  hugeicons: "SearchIcon",
  phosphor: "MagnifyingGlassIcon",
  remixicon: "RiSearchLine",
})
export const Forward = createSiteIcon(LucideForward, {
  tabler: "IconArrowForwardUp",
  hugeicons: "ArrowTurnForwardIcon",
  phosphor: "ArrowBendUpRightIcon",
  remixicon: "RiShareForwardLine",
})
export const Frame = createSiteIcon(LucideFrame, {
  tabler: "IconFrame",
  hugeicons: "CropIcon",
  phosphor: "CropIcon",
  remixicon: "RiCropLine",
})
export const FrameIcon = createSiteIcon(LucideFrameIcon, {
  tabler: "IconFrame",
  hugeicons: "CropIcon",
  phosphor: "CropIcon",
  remixicon: "RiCropLine",
})
export const GalleryVerticalEnd = createSiteIcon(LucideGalleryVerticalEnd, {
  tabler: "IconLayoutRows",
  hugeicons: "LayoutBottomIcon",
  phosphor: "RowsIcon",
  remixicon: "RiGalleryLine",
})
export const GitBranchIcon = createSiteIcon(LucideGitBranchIcon, {
  tabler: "IconGitBranch",
  hugeicons: "GitBranchIcon",
  phosphor: "GitBranchIcon",
  remixicon: "RiGitBranchLine",
})
export const GlobeIcon = createSiteIcon(LucideGlobeIcon, {
  tabler: "IconWorld",
  hugeicons: "Globe02Icon",
  phosphor: "GlobeIcon",
  remixicon: "RiGlobalLine",
})
export const HelpCircle = createSiteIcon(LucideHelpCircle, {
  tabler: "IconHelpCircle",
  hugeicons: "HelpCircleIcon",
  phosphor: "QuestionIcon",
  remixicon: "RiQuestionLine",
})
export const HelpCircleIcon = createSiteIcon(LucideHelpCircleIcon, {
  tabler: "IconHelpCircle",
  hugeicons: "HelpCircleIcon",
  phosphor: "QuestionIcon",
  remixicon: "RiQuestionLine",
})
export const HistoryIcon = createSiteIcon(LucideHistoryIcon, {})
export const HomeIcon = createSiteIcon(LucideHomeIcon, {
  tabler: "IconHome",
  hugeicons: "HomeIcon",
  phosphor: "HouseIcon",
  remixicon: "RiHomeLine",
})
export const ImageIcon = createSiteIcon(LucideImageIcon, {
  tabler: "IconPhoto",
  hugeicons: "Image01Icon",
  phosphor: "ImageIcon",
  remixicon: "RiImageLine",
})
export const InboxIcon = createSiteIcon(LucideInboxIcon, {
  tabler: "IconInbox",
  hugeicons: "InboxIcon",
  phosphor: "TrayIcon",
  remixicon: "RiInboxLine",
})
export const InfoIcon = createSiteIcon(LucideInfoIcon, {
  tabler: "IconInfoCircle",
  hugeicons: "AlertCircleIcon",
  phosphor: "InfoIcon",
  remixicon: "RiInformationLine",
})
export const Italic = createSiteIcon(LucideItalic, {
  tabler: "IconItalic",
  hugeicons: "TextItalicIcon",
  phosphor: "TextItalicIcon",
  remixicon: "RiItalic",
})
export const ItalicIcon = createSiteIcon(LucideItalicIcon, {
  tabler: "IconItalic",
  hugeicons: "TextItalicIcon",
  phosphor: "TextItalicIcon",
  remixicon: "RiItalic",
})
export const KeyboardIcon = createSiteIcon(LucideKeyboardIcon, {
  tabler: "IconKeyboard",
  hugeicons: "KeyboardIcon",
  phosphor: "KeyboardIcon",
  remixicon: "RiKeyboardLine",
})
export const LanguagesIcon = createSiteIcon(LucideLanguagesIcon, {
  tabler: "IconLanguage",
  hugeicons: "LanguageCircleIcon",
  phosphor: "TranslateIcon",
  remixicon: "RiTranslate",
})
export const LayersIcon = createSiteIcon(LucideLayersIcon, {
  tabler: "IconStack2",
  hugeicons: "Layers01Icon",
  phosphor: "StackIcon",
  remixicon: "RiStackLine",
})
export const LayoutGridIcon = createSiteIcon(LucideLayoutGridIcon, {
  tabler: "IconLayoutGrid",
  hugeicons: "GridIcon",
  phosphor: "GridFourIcon",
  remixicon: "RiGridLine",
})
export const LayoutIcon = createSiteIcon(LucideLayoutIcon, {
  tabler: "IconLayout",
  hugeicons: "LayoutIcon",
  phosphor: "LayoutIcon",
  remixicon: "RiLayoutLine",
})
export const LifeBuoyIcon = createSiteIcon(LucideLifeBuoyIcon, {
  tabler: "IconLifebuoy",
  hugeicons: "ChartRingIcon",
  phosphor: "LifebuoyIcon",
  remixicon: "RiLifebuoyLine",
})
export const Link2Icon = createSiteIcon(LucideLink2Icon, {
  tabler: "IconLink",
  hugeicons: "Link02Icon",
  phosphor: "LinkSimpleIcon",
  remixicon: "RiLinksLine",
})
export const ListFilterIcon = createSiteIcon(LucideListFilterIcon, {
  tabler: "IconFilter",
  hugeicons: "FilterHorizontalIcon",
  phosphor: "FunnelSimpleIcon",
  remixicon: "RiFilter3Line",
})
export const ListIcon = createSiteIcon(LucideListIcon, {
  tabler: "IconListDetails",
  hugeicons: "Menu01Icon",
  phosphor: "ListIcon",
  remixicon: "RiListUnordered",
})
export const Loader2Icon = createSiteIcon(LucideLoader2Icon, {
  tabler: "IconLoader",
  hugeicons: "Loading03Icon",
  phosphor: "SpinnerIcon",
  remixicon: "RiLoaderLine",
})
export const LoaderIcon = createSiteIcon(LucideLoaderIcon, {
  tabler: "IconLoader",
  hugeicons: "Loading03Icon",
  phosphor: "SpinnerIcon",
  remixicon: "RiLoader4Line",
})
export const LogOut = createSiteIcon(LucideLogOut, {
  tabler: "IconLogout",
  hugeicons: "Logout01Icon",
  phosphor: "SignOutIcon",
  remixicon: "RiLogoutBoxLine",
})
export const LogOutIcon = createSiteIcon(LucideLogOutIcon, {
  tabler: "IconLogout",
  hugeicons: "Logout01Icon",
  phosphor: "SignOutIcon",
  remixicon: "RiLogoutBoxLine",
})
export const MailCheckIcon = createSiteIcon(LucideMailCheckIcon, {
  tabler: "IconMailCheck",
  hugeicons: "MailValidation01Icon",
  phosphor: "EnvelopeOpenIcon",
  remixicon: "RiMailCheckLine",
})
export const MailIcon = createSiteIcon(LucideMailIcon, {
  tabler: "IconMail",
  hugeicons: "Mail01Icon",
  phosphor: "EnvelopeIcon",
  remixicon: "RiMailLine",
})
export const Map = createSiteIcon(LucideMap, {
  tabler: "IconMap",
  hugeicons: "MapsIcon",
  phosphor: "MapTrifoldIcon",
  remixicon: "RiMapLine",
})
export const MapIcon = createSiteIcon(LucideMapIcon, {
  tabler: "IconMap",
  hugeicons: "MapsIcon",
  phosphor: "MapTrifoldIcon",
  remixicon: "RiMapLine",
})
export const MaximizeIcon = createSiteIcon(LucideMaximizeIcon, {
  tabler: "IconMaximize",
  hugeicons: "PlusSignIcon",
  phosphor: "PlusIcon",
  remixicon: "RiAddLine",
})
export const MessageCircleDashedIcon = createSiteIcon(
  LucideMessageCircleDashedIcon,
  {
    tabler: "IconMessageCircle",
    hugeicons: "BubbleChatIcon",
    phosphor: "ChatCircleDotsIcon",
    remixicon: "RiChat3Line",
  }
)
export const MessageSquareIcon = createSiteIcon(LucideMessageSquareIcon, {
  tabler: "IconMessage",
  hugeicons: "Message01Icon",
  phosphor: "ChatIcon",
  remixicon: "RiChat1Line",
})
export const MicIcon = createSiteIcon(LucideMicIcon, {
  tabler: "IconMicrophone",
  hugeicons: "VoiceIcon",
  phosphor: "MicrophoneIcon",
  remixicon: "RiMicLine",
})
export const MinimizeIcon = createSiteIcon(LucideMinimizeIcon, {
  tabler: "IconMinimize",
  hugeicons: "MinusSignIcon",
  phosphor: "MinusIcon",
  remixicon: "RiSubtractLine",
})
export const Minus = createSiteIcon(LucideMinus, {
  tabler: "IconMinus",
  hugeicons: "MinusSignIcon",
  phosphor: "MinusIcon",
  remixicon: "RiSubtractLine",
})
export const MinusIcon = createSiteIcon(LucideMinusIcon, {
  tabler: "IconMinus",
  hugeicons: "MinusSignIcon",
  phosphor: "MinusIcon",
  remixicon: "RiSubtractLine",
})
export const MonitorIcon = createSiteIcon(LucideMonitorIcon, {
  tabler: "IconDeviceDesktop",
  hugeicons: "ComputerIcon",
  phosphor: "MonitorIcon",
  remixicon: "RiComputerLine",
})
export const MoonIcon = createSiteIcon(LucideMoonIcon, {
  tabler: "IconMoon",
  hugeicons: "MoonIcon",
  phosphor: "MoonIcon",
  remixicon: "RiMoonLine",
})
export const MoreHorizontal = createSiteIcon(LucideMoreHorizontal, {
  tabler: "IconDots",
  hugeicons: "MoreHorizontalCircle01Icon",
  phosphor: "DotsThreeOutlineIcon",
  remixicon: "RiMoreLine",
})
export const MoreHorizontalIcon = createSiteIcon(LucideMoreHorizontalIcon, {
  tabler: "IconDots",
  hugeicons: "MoreHorizontalCircle01Icon",
  phosphor: "DotsThreeOutlineIcon",
  remixicon: "RiMoreLine",
})
export const OctagonXIcon = createSiteIcon(LucideOctagonXIcon, {
  tabler: "IconAlertOctagon",
  hugeicons: "MultiplicationSignCircleIcon",
  phosphor: "XCircleIcon",
  remixicon: "RiCloseCircleLine",
})
export const PaletteIcon = createSiteIcon(LucidePaletteIcon, {
  tabler: "IconPalette",
  hugeicons: "PaintBoardIcon",
  phosphor: "PaletteIcon",
  remixicon: "RiPaletteLine",
})
export const PanelLeftCloseIcon = createSiteIcon(LucidePanelLeftCloseIcon, {
  tabler: "IconLayoutSidebarLeftCollapse",
  hugeicons: "SidebarLeft01Icon",
  phosphor: "SidebarSimpleIcon",
  remixicon: "RiSidebarFoldLine",
})
export const PanelLeftIcon = createSiteIcon(LucidePanelLeftIcon, {
  tabler: "IconLayoutSidebar",
  hugeicons: "SidebarLeftIcon",
  phosphor: "SidebarIcon",
  remixicon: "RiLayoutLeftLine",
})
export const PanelLeftOpenIcon = createSiteIcon(LucidePanelLeftOpenIcon, {
  tabler: "IconLayoutSidebarLeftExpand",
  hugeicons: "SidebarLeftIcon",
  phosphor: "SidebarIcon",
  remixicon: "RiSidebarUnfoldLine",
})
export const PaperclipIcon = createSiteIcon(LucidePaperclipIcon, {
  tabler: "IconPaperclip",
  hugeicons: "AttachmentIcon",
  phosphor: "PaperclipIcon",
  remixicon: "RiAttachmentLine",
})
export const PencilIcon = createSiteIcon(LucidePencilIcon, {
  tabler: "IconPencil",
  hugeicons: "EditIcon",
  phosphor: "PencilIcon",
  remixicon: "RiPencilLine",
})
export const PieChart = createSiteIcon(LucidePieChart, {
  tabler: "IconChartPie",
  hugeicons: "PieChartIcon",
  phosphor: "ChartPieIcon",
  remixicon: "RiPieChartLine",
})
export const PieChartIcon = createSiteIcon(LucidePieChartIcon, {
  tabler: "IconChartPie",
  hugeicons: "PieChartIcon",
  phosphor: "ChartPieIcon",
  remixicon: "RiPieChartLine",
})
export const Plus = createSiteIcon(LucidePlus, {
  tabler: "IconPlus",
  hugeicons: "Add01Icon",
  phosphor: "PlusIcon",
  remixicon: "RiAddLine",
})
export const PlusIcon = createSiteIcon(LucidePlusIcon, {
  tabler: "IconPlus",
  hugeicons: "Add01Icon",
  phosphor: "PlusIcon",
  remixicon: "RiAddLine",
})
export const RadioIcon = createSiteIcon(LucideRadioIcon, {
  tabler: "IconPlayerRecordFilled",
  hugeicons: "RecordIcon",
  phosphor: "RecordIcon",
  remixicon: "RiRecordCircleLine",
})
export const RectangleHorizontalIcon = createSiteIcon(
  LucideRectangleHorizontalIcon,
  {}
)
export const RectangleVerticalIcon = createSiteIcon(
  LucideRectangleVerticalIcon,
  {}
)
export const RefreshCcwIcon = createSiteIcon(LucideRefreshCcwIcon, {
  tabler: "IconRefresh",
  hugeicons: "ReloadIcon",
  phosphor: "ArrowClockwiseIcon",
  remixicon: "RiRefreshLine",
})
export const RefreshCwIcon = createSiteIcon(LucideRefreshCwIcon, {
  tabler: "IconRefresh",
  hugeicons: "RepeatIcon",
  phosphor: "ArrowsClockwiseIcon",
  remixicon: "RiRefreshLine",
})
export const RotateCcwIcon = createSiteIcon(LucideRotateCcwIcon, {
  tabler: "IconRotate",
  hugeicons: "RotateLeft01Icon",
  phosphor: "ArrowCounterClockwiseIcon",
  remixicon: "RiResetLeftLine",
})
export const RotateCwIcon = createSiteIcon(LucideRotateCwIcon, {
  tabler: "IconRotateClockwise2",
  hugeicons: "Rotate01Icon",
  phosphor: "ArrowClockwiseIcon",
  remixicon: "RiRefreshLine",
})
export const SaveIcon = createSiteIcon(LucideSaveIcon, {
  tabler: "IconDeviceFloppy",
  hugeicons: "FloppyDiskIcon",
  phosphor: "FloppyDiskIcon",
  remixicon: "RiSaveLine",
})
export const ScissorsIcon = createSiteIcon(LucideScissorsIcon, {
  tabler: "IconCut",
  hugeicons: "ScissorIcon",
  phosphor: "ScissorsIcon",
  remixicon: "RiScissorsLine",
})
export const Search = createSiteIcon(LucideSearch, {
  tabler: "IconSearch",
  hugeicons: "SearchIcon",
  phosphor: "MagnifyingGlassIcon",
  remixicon: "RiSearchLine",
})
export const SearchIcon = createSiteIcon(LucideSearchIcon, {
  tabler: "IconSearch",
  hugeicons: "SearchIcon",
  phosphor: "MagnifyingGlassIcon",
  remixicon: "RiSearchLine",
})
export const SendIcon = createSiteIcon(LucideSendIcon, {
  tabler: "IconSend",
  hugeicons: "SentIcon",
  phosphor: "PaperPlaneTiltIcon",
  remixicon: "RiSendPlaneLine",
})
export const Settings = createSiteIcon(LucideSettings, {
  tabler: "IconSettings",
  hugeicons: "SettingsIcon",
  phosphor: "GearIcon",
  remixicon: "RiSettingsLine",
})
export const Settings2 = createSiteIcon(LucideSettings2, {
  tabler: "IconSettings",
  hugeicons: "Settings05Icon",
  phosphor: "GearIcon",
  remixicon: "RiSettingsLine",
})
export const SettingsIcon = createSiteIcon(LucideSettingsIcon, {
  tabler: "IconSettings",
  hugeicons: "SettingsIcon",
  phosphor: "GearIcon",
  remixicon: "RiSettingsLine",
})
export const ShareIcon = createSiteIcon(LucideShareIcon, {
  tabler: "IconShare3",
  hugeicons: "Share01Icon",
  phosphor: "ShareIcon",
  remixicon: "RiShareLine",
})
export const ShieldAlertIcon = createSiteIcon(LucideShieldAlertIcon, {
  tabler: "IconShieldExclamation",
  hugeicons: "Shield01Icon",
  phosphor: "ShieldWarningIcon",
  remixicon: "RiShieldFlashLine",
})
export const ShieldIcon = createSiteIcon(LucideShieldIcon, {
  tabler: "IconShield",
  hugeicons: "ShieldIcon",
  phosphor: "ShieldIcon",
  remixicon: "RiShieldLine",
})
export const Smile = createSiteIcon(LucideSmile, {
  tabler: "IconMoodSmile",
  hugeicons: "SmileIcon",
  phosphor: "SmileyIcon",
  remixicon: "RiEmotionLine",
})
export const SmileIcon = createSiteIcon(LucideSmileIcon, {
  tabler: "IconMoodSmile",
  hugeicons: "SmileIcon",
  phosphor: "SmileyIcon",
  remixicon: "RiEmotionLine",
})
export const Sparkles = createSiteIcon(LucideSparkles, {
  tabler: "IconSparkles",
  hugeicons: "SparklesIcon",
  phosphor: "SparkleIcon",
  remixicon: "RiSparklingLine",
})
export const SparklesIcon = createSiteIcon(LucideSparklesIcon, {
  tabler: "IconSparkles",
  hugeicons: "SparklesIcon",
  phosphor: "SparkleIcon",
  remixicon: "RiSparklingLine",
})
export const SquareIcon = createSiteIcon(LucideSquareIcon, {
  tabler: "IconPlayerStop",
  hugeicons: "StopCircleIcon",
  phosphor: "StopCircleIcon",
  remixicon: "RiStopCircleLine",
})
export const SquarePenIcon = createSiteIcon(LucideSquarePenIcon, {})
export const SquareTerminal = createSiteIcon(LucideSquareTerminal, {
  tabler: "IconTerminal2",
  hugeicons: "ComputerTerminal01Icon",
  phosphor: "TerminalWindowIcon",
  remixicon: "RiTerminalBoxLine",
})
export const SquareTerminalIcon = createSiteIcon(LucideSquareTerminalIcon, {
  tabler: "IconTerminal2",
  hugeicons: "ComputerTerminal01Icon",
  phosphor: "TerminalWindowIcon",
  remixicon: "RiTerminalBoxLine",
})
export const StarIcon = createSiteIcon(LucideStarIcon, {
  tabler: "IconStar",
  hugeicons: "StarIcon",
  phosphor: "StarIcon",
  remixicon: "RiStarLine",
})
export const SunIcon = createSiteIcon(LucideSunIcon, {
  tabler: "IconSun",
  hugeicons: "Sun03Icon",
  phosphor: "SunIcon",
  remixicon: "RiSunLine",
})
export const TableIcon = createSiteIcon(LucideTableIcon, {
  tabler: "IconTable",
  hugeicons: "TableIcon",
  phosphor: "TableIcon",
  remixicon: "RiTableLine",
})
export const TagIcon = createSiteIcon(LucideTagIcon, {
  tabler: "IconTag",
  hugeicons: "Tag01Icon",
  phosphor: "TagIcon",
  remixicon: "RiPriceTag3Line",
})
export const TelescopeIcon = createSiteIcon(LucideTelescopeIcon, {
  tabler: "IconTelescope",
  hugeicons: "Telescope01Icon",
  phosphor: "BinocularsIcon",
  remixicon: "RiSearchEyeLine",
})
export const ThumbsDownIcon = createSiteIcon(LucideThumbsDownIcon, {
  tabler: "IconThumbDown",
  hugeicons: "ThumbsDownIcon",
  phosphor: "ThumbsDownIcon",
  remixicon: "RiThumbDownLine",
})
export const ThumbsUpIcon = createSiteIcon(LucideThumbsUpIcon, {
  tabler: "IconThumbUp",
  hugeicons: "ThumbsUpIcon",
  phosphor: "ThumbsUpIcon",
  remixicon: "RiThumbUpLine",
})
export const Trash2 = createSiteIcon(LucideTrash2, {
  tabler: "IconTrash",
  hugeicons: "Delete02Icon",
  phosphor: "TrashIcon",
  remixicon: "RiDeleteBinLine",
})
export const Trash2Icon = createSiteIcon(LucideTrash2Icon, {
  tabler: "IconTrash",
  hugeicons: "Delete02Icon",
  phosphor: "TrashIcon",
  remixicon: "RiDeleteBinLine",
})
export const TrashIcon = createSiteIcon(LucideTrashIcon, {
  tabler: "IconTrash",
  hugeicons: "DeleteIcon",
  phosphor: "TrashIcon",
  remixicon: "RiDeleteBinLine",
})
export const TriangleAlertIcon = createSiteIcon(LucideTriangleAlertIcon, {
  tabler: "IconAlertTriangle",
  hugeicons: "Alert02Icon",
  phosphor: "WarningIcon",
  remixicon: "RiErrorWarningLine",
})
export const Underline = createSiteIcon(LucideUnderline, {
  tabler: "IconUnderline",
  hugeicons: "TextUnderlineIcon",
  phosphor: "TextUnderlineIcon",
  remixicon: "RiUnderline",
})
export const UnderlineIcon = createSiteIcon(LucideUnderlineIcon, {
  tabler: "IconUnderline",
  hugeicons: "TextUnderlineIcon",
  phosphor: "TextUnderlineIcon",
  remixicon: "RiUnderline",
})
export const User = createSiteIcon(LucideUser, {
  tabler: "IconUser",
  hugeicons: "UserIcon",
  phosphor: "UserIcon",
  remixicon: "RiUserLine",
})
export const UserIcon = createSiteIcon(LucideUserIcon, {
  tabler: "IconUser",
  hugeicons: "UserIcon",
  phosphor: "UserIcon",
  remixicon: "RiUserLine",
})
export const UserRoundXIcon = createSiteIcon(LucideUserRoundXIcon, {
  tabler: "IconUserX",
  hugeicons: "UserRemove01Icon",
  phosphor: "UserMinusIcon",
  remixicon: "RiUserUnfollowLine",
})
export const UsersIcon = createSiteIcon(LucideUsersIcon, {
  tabler: "IconUsers",
  hugeicons: "UserGroupIcon",
  phosphor: "UsersIcon",
  remixicon: "RiGroupLine",
})
export const VolumeOffIcon = createSiteIcon(LucideVolumeOffIcon, {
  tabler: "IconVolume",
  hugeicons: "VolumeOffIcon",
  phosphor: "SpeakerSlashIcon",
  remixicon: "RiVolumeMuteLine",
})
export const WalletIcon = createSiteIcon(LucideWalletIcon, {
  tabler: "IconWallet",
  hugeicons: "Wallet01Icon",
  phosphor: "WalletIcon",
  remixicon: "RiWalletLine",
})
export const XIcon = createSiteIcon(LucideXIcon, {
  tabler: "IconX",
  hugeicons: "Cancel01Icon",
  phosphor: "XIcon",
  remixicon: "RiCloseLine",
})
export const ZoomInIcon = createSiteIcon(LucideZoomInIcon, {
  tabler: "IconZoomIn",
  hugeicons: "ZoomInAreaIcon",
  phosphor: "MagnifyingGlassPlusIcon",
  remixicon: "RiZoomInLine",
})
export const ZoomOutIcon = createSiteIcon(LucideZoomOutIcon, {
  tabler: "IconZoomOut",
  hugeicons: "ZoomOutAreaIcon",
  phosphor: "MagnifyingGlassMinusIcon",
  remixicon: "RiSearchEyeLine",
})
