"use client"

import * as React from "react"
import { HugeiconsIcon, type IconSvgElement } from "@hugeicons/react"
import type { LucideIcon, LucideProps } from "lucide-react"

import { useSiteSetting, type SiteIconLibrary } from "@/lib/site-settings"

// Runtime for lib/site-icons.tsx (generated by scripts/build-icons.ts): each
// Lucide icon the site's previews import becomes a component that renders the
// icon pack picked in the site settings. Lucide renders straight away (it is
// the default, and what the server renders); the other packs load on demand.

type OtherLibrary = Exclude<SiteIconLibrary, "lucide">

export type SiteIconMapping = Partial<Record<OtherLibrary, string>>

const LIBRARY_MODULES: Record<
  OtherLibrary,
  () => Promise<Record<string, unknown>>
> = {
  tabler: () => import("./site-icons.tabler"),
  hugeicons: () => import("./site-icons.hugeicons"),
  phosphor: () => import("./site-icons.phosphor"),
  remixicon: () => import("./site-icons.remixicon"),
}

const loaded = new Map<OtherLibrary, Promise<Record<string, unknown>>>()

function loadLibrary(library: OtherLibrary) {
  let promise = loaded.get(library)
  if (!promise) {
    promise = LIBRARY_MODULES[library]()
    loaded.set(library, promise)
  }
  return promise
}

type IconProps = Omit<LucideProps, "absoluteStrokeWidth">

function LibraryIcon({
  library,
  name,
  ...props
}: IconProps & { library: OtherLibrary; name: string }) {
  const icons = React.use(loadLibrary(library))
  const icon = icons[name]

  if (!icon) {
    return null
  }

  // HugeIcons exports icon data, rendered through its own component.
  if (Array.isArray(icon)) {
    const { strokeWidth, ...rest } = props
    return (
      <HugeiconsIcon
        icon={icon as IconSvgElement}
        strokeWidth={strokeWidth === undefined ? 2 : Number(strokeWidth)}
        {...rest}
      />
    )
  }

  const Icon = icon as React.ComponentType<IconProps>
  return <Icon {...props} />
}

export function createSiteIcon(
  Lucide: LucideIcon,
  mapping: SiteIconMapping
): LucideIcon {
  function SiteIcon({ absoluteStrokeWidth, ...props }: LucideProps) {
    const [library] = useSiteSetting("iconLibrary")
    const name = library === "lucide" ? undefined : mapping[library]

    if (library === "lucide" || !name) {
      return <Lucide absoluteStrokeWidth={absoluteStrokeWidth} {...props} />
    }

    return (
      <React.Suspense fallback={<Lucide {...props} />}>
        {/* Lucide draws at 24px by default; Phosphor would use 1em. */}
        <LibraryIcon
          library={library}
          name={name}
          {...props}
          size={props.size ?? 24}
        />
      </React.Suspense>
    )
  }

  SiteIcon.displayName = Lucide.displayName
  return SiteIcon as unknown as LucideIcon
}
